# Generated by Django 3.0.8 on 2020-09-21 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsManagement', '0002_auto_20200921_2318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PastProject',
        ),
    ]
