# Generated by Django 3.0.8 on 2020-09-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsManagement', '0004_plannedproject_working_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeworkingproject',
            name='ready_for_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
