# Generated by Django 3.0.8 on 2021-01-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Careers', '0003_auto_20201011_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipsappliance',
            name='curriculum_vitae',
            field=models.FileField(default='default.pdf', upload_to='internships_curriculum_vitae/'),
        ),
    ]
