# Generated by Django 3.0.8 on 2021-01-24 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Careers', '0004_auto_20210124_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsappliance',
            name='curriculum_vitae',
        ),
    ]
