# Generated by Django 3.0.8 on 2021-01-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Careers', '0005_remove_jobsappliance_curriculum_vitae'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsappliance',
            name='curriculum_vitae',
            field=models.FileField(default='default.pdf', upload_to='curriculum_vitae/'),
        ),
    ]
