# Generated by Django 3.0.8 on 2020-08-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('submitted', models.BooleanField(default=True)),
                ('answer_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
