# Generated by Django 3.0.8 on 2020-08-10 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainView', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmanswer',
            name='name',
        ),
    ]
