# Generated by Django 3.0.8 on 2020-08-10 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainView', '0002_remove_confirmanswer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmanswer',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='confirmanswer',
            name='answer_sent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='confirmanswer',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
