# Generated by Django 3.0.8 on 2020-08-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainView', '0005_auto_20200810_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmanswer',
            name='answer_sent',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
