# Generated by Django 3.0.8 on 2020-08-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainView', '0008_confirmanswer_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmanswer',
            name='answer_sent',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
