# Generated by Django 3.0.8 on 2020-08-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainView', '0015_auto_20200819_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestenvironmentdetail',
            name='table_image',
            field=models.ImageField(blank=True, upload_to='guests_tables_images/'),
        ),
        migrations.AlterField(
            model_name='guestenvironmentdetail',
            name='table_number',
            field=models.IntegerField(default=0),
        ),
    ]
