# Generated by Django 3.0.8 on 2020-09-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainView', '0016_auto_20200819_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestenvironmentdetail',
            name='position',
            field=models.IntegerField(choices=[(0, 'Guest'), (1, 'Bridesmaid'), (2, 'Groomsmen'), (3, 'Godparent'), (4, 'Parent')], default=0),
        ),
    ]
