# Generated by Django 3.0.8 on 2020-10-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainView', '0020_auto_20200917_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmanswer',
            name='position',
            field=models.CharField(choices=[('Guest', 'Our Guest'), ('Bridesmaid', 'Our Bridesmaid'), ('Groomsmen', 'Our Groomsmen'), ('Godparent', 'Our Godparent'), ('Parent', 'Our Parent'), ('Husband', 'My Husband'), ('Wife', 'My Wife')], default=0, max_length=25),
        ),
    ]
