# Generated by Django 3.0.8 on 2020-10-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Careers', '0002_auto_20201011_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableinternship',
            name='job_type',
            field=models.CharField(choices=[('Remote', 'Remote'), ('OnSite', 'OnSite')], default='OnSite', max_length=100),
        ),
        migrations.AlterField(
            model_name='availablejob',
            name='job_type',
            field=models.CharField(choices=[('Remote', 'Remote'), ('OnSite', 'OnSite')], default='OnSite', max_length=100),
        ),
    ]
