# Generated by Django 3.0.8 on 2020-10-06 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20201007_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='manager_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='manager_name',
        ),
    ]
