# Generated by Django 3.0.8 on 2020-10-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20201007_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_image',
            field=models.ImageField(default='default.jpg', upload_to='authors_images/'),
        ),
    ]
