# Generated by Django 3.0.8 on 2020-10-25 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsManagement', '0007_activeworkingproject_percent_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeworkingproject',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='plannedproject',
            name='deadline_for_production',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
