# Generated by Django 3.0.8 on 2020-11-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsManagement', '0008_auto_20201025_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeworkingproject',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
