# Generated by Django 3.0.8 on 2020-11-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsManagement', '0009_auto_20201106_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activeworkingproject',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='finishedproject',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='plannedproject',
            options={'ordering': ['-date']},
        ),
    ]
