# Generated by Django 3.0.8 on 2020-11-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsManagement', '0010_auto_20201108_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeworkingproject',
            name='active_working_project_slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='finishedproject',
            name='finished_project_slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='plannedproject',
            name='planned_project_slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
