# Generated by Django 3.0.8 on 2021-01-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_representation',
            field=models.ImageField(default='default.jpg', upload_to='blog_cover_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='wallpaper_representation',
            field=models.ImageField(default='default.jpg', upload_to='blog_wallpaper_images/'),
        ),
    ]
