# Generated by Django 3.0.8 on 2020-10-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsManagement', '0009_auto_20201022_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagestoclient',
            name='message_slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
