# Generated by Django 3.0.8 on 2020-10-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_post_author_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_image',
        ),
    ]
