# Generated by Django 3.0.8 on 2020-08-17 23:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MainView', '0007_remove_confirmanswer_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmanswer',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
