# Generated by Django 3.0.8 on 2020-09-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainView', '0017_guestenvironmentdetail_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestenvironmentdetail',
            name='position',
            field=models.IntegerField(choices=[(0, 'Guest'), (1, 'Bridesmaid'), (2, 'Groomsmen'), (3, 'Godparent'), (4, 'Parent'), (5, 'Husband'), (6, 'Wife')], default=0),
        ),
    ]
