# Generated by Django 3.0.8 on 2020-10-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainView', '0021_auto_20201019_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmanswer',
            name='position',
            field=models.CharField(choices=[('Our Guest', 'Our Guest'), ('Our Bridesmaid', 'Our Bridesmaid'), ('Our Groomsmen', 'Our Groomsmen'), ('Our Godparent', 'Our Godparent'), ('Our Parent', 'Our Parent'), ('My Husband', 'My Husband'), ('My Wife', 'My Wife')], default=0, max_length=25),
        ),
    ]
