# Generated by Django 3.0.8 on 2020-10-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Communication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='read',
        ),
    ]
