# Generated by Django 3.0.8 on 2020-09-21 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsManagement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PastProduct',
        ),
    ]
