# Generated by Django 3.0.8 on 2020-11-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsManagement', '0013_auto_20201025_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagestoclient',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
