# Generated by Django 3.0.8 on 2020-11-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsManagement', '0023_auto_20201109_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsdetail',
            name='profile_image',
            field=models.ImageField(default='/clients-profile-images/default.jpg', upload_to='clients-profile-images/'),
        ),
    ]
