# Generated by Django 3.0.8 on 2020-11-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsManagement', '0007_auto_20201110_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedproduct',
            name='planned_product_slug',
            field=models.SlugField(default='X', max_length=200, unique=True),
        ),
    ]
