# Generated by Django 3.0.8 on 2021-01-15 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_auto_20210115_1331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageClient',
            new_name='ImagesClient',
        ),
    ]
