# Generated by Django 3.0.8 on 2021-01-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0005_auto_20210116_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesclient',
            name='image',
            field=models.ImageField(upload_to='specific_user_gallery_images/'),
        ),
    ]
