# Generated by Django 3.0.8 on 2021-02-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0007_platformpresentationimage_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesclient',
            name='column',
            field=models.CharField(choices=[('First Column', 'First Column'), ('Second Column', 'Second Column'), ('Third Column', 'Third Column'), ('Fourth Column', 'Fourth Column')], default='First Column', max_length=255),
        ),
    ]
