# Generated by Django 3.0.8 on 2021-02-23 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0008_imagesclient_column'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagesclient',
            old_name='default',
            new_name='pick_image',
        ),
    ]
