# Generated by Django 3.0.8 on 2021-02-25 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0009_auto_20210223_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gallery.ImagesClient')),
            ],
        ),
    ]
