# Generated by Django 3.0.8 on 2021-02-25 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0011_auto_20210225_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickedimage',
            name='back_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='back_image', to='Gallery.ImagesClient'),
        ),
        migrations.AddField(
            model_name='pickedimage',
            name='content_image_four',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='content_image_four', to='Gallery.ImagesClient'),
        ),
        migrations.AddField(
            model_name='pickedimage',
            name='content_image_one',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='content_image_one', to='Gallery.ImagesClient'),
        ),
        migrations.AddField(
            model_name='pickedimage',
            name='content_image_three',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='content_image_three', to='Gallery.ImagesClient'),
        ),
        migrations.AddField(
            model_name='pickedimage',
            name='content_image_two',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='content_image_two', to='Gallery.ImagesClient'),
        ),
        migrations.RemoveField(
            model_name='pickedimage',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='pickedimage',
            name='cover_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cover_image', to='Gallery.ImagesClient'),
        ),
    ]
