# Generated by Django 3.0.8 on 2021-02-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0012_auto_20210225_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagesclient',
            old_name='pick_image',
            new_name='pick_back_image',
        ),
        migrations.AddField(
            model_name='imagesclient',
            name='pick_content_image_four',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagesclient',
            name='pick_content_image_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagesclient',
            name='pick_content_image_three',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagesclient',
            name='pick_content_image_two',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagesclient',
            name='pick_cover_image',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PickedImage',
        ),
    ]
