# Generated by Django 3.0.8 on 2021-02-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0013_auto_20210225_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesclient',
            name='our_thoughts',
            field=models.TextField(default=''),
        ),
    ]
