# Generated by Django 3.0.8 on 2021-02-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0014_imagesclient_our_thoughts'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesclient',
            name='image_slug',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
