# Generated by Django 3.0.8 on 2021-02-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0015_imagesclient_image_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesclient',
            name='pick_back_image',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='imagesclient',
            name='pick_content_image_four',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='imagesclient',
            name='pick_content_image_one',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='imagesclient',
            name='pick_content_image_three',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='imagesclient',
            name='pick_content_image_two',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='imagesclient',
            name='pick_cover_image',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
