# Generated by Django 3.1.7 on 2021-03-01 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gallery', '0018_auto_20210225_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesclient',
            name='pick_back_image',
        ),
        migrations.RemoveField(
            model_name='imagesclient',
            name='pick_content_image_four',
        ),
        migrations.RemoveField(
            model_name='imagesclient',
            name='pick_content_image_one',
        ),
        migrations.RemoveField(
            model_name='imagesclient',
            name='pick_content_image_three',
        ),
        migrations.RemoveField(
            model_name='imagesclient',
            name='pick_content_image_two',
        ),
        migrations.RemoveField(
            model_name='imagesclient',
            name='pick_cover_image',
        ),
        migrations.CreateModel(
            name='ClientCatalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clients_catalogue/')),
                ('pick_cover_image', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=5)),
                ('pick_content_image_one', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=5)),
                ('pick_content_image_two', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=5)),
                ('pick_content_image_three', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=5)),
                ('pick_content_image_four', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=5)),
                ('pick_back_image', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=5)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
