# Generated by Django 3.1.7 on 2021-03-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0019_auto_20210301_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcatalogue',
            name='pick_content_image_one',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='clientcatalogue',
            name='pick_cover_image',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5),
        ),
    ]
