# Generated by Django 3.1.7 on 2021-03-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0020_auto_20210301_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcatalogue',
            name='pick_back_image',
        ),
        migrations.RemoveField(
            model_name='clientcatalogue',
            name='pick_content_image_four',
        ),
        migrations.RemoveField(
            model_name='clientcatalogue',
            name='pick_content_image_one',
        ),
        migrations.RemoveField(
            model_name='clientcatalogue',
            name='pick_content_image_three',
        ),
        migrations.RemoveField(
            model_name='clientcatalogue',
            name='pick_content_image_two',
        ),
        migrations.RemoveField(
            model_name='clientcatalogue',
            name='pick_cover_image',
        ),
        migrations.AddField(
            model_name='clientcatalogue',
            name='image_positioning',
            field=models.CharField(choices=[('Cover Image', 'Cover Image'), ('Content Image One', 'Content Image One'), ('Content Image Two', 'Content Image Two'), ('Content Image Three', 'Content Image Three'), ('Content Image Four', 'Content Image Four'), ('Back Image', 'Back Image'), ('None of it', 'None of it')], default='None of it', max_length=255),
        ),
    ]
