# Generated by Django 3.1.7 on 2021-03-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0021_auto_20210301_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcatalogue',
            name='image_positioning',
            field=models.CharField(choices=[('Cover Image', 'Cover Image'), ('Content Image', 'Content Image'), ('Back Image', 'Back Image'), ('None of it', 'None of it')], default='None of it', max_length=255),
        ),
    ]
