# Generated by Django 3.0.8 on 2020-09-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsManagement', '0005_clientinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='type_of_client',
            field=models.CharField(choices=[('Small Client', 'Small Client'), ('Medium Client', 'Medium Client'), ('Big Client', 'Big Client'), ('Huge Client', 'Huge Client')], default='Small Client', max_length=100),
        ),
    ]
