# Generated by Django 3.0.8 on 2020-09-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsManagement', '0006_auto_20200922_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='askproject',
            name='project_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Refused', 'Refused'), ('Accepted', 'Accepted')], default='Processing', max_length=100),
        ),
    ]
