# Generated by Django 3.0.8 on 2020-11-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsManagement', '0014_messagestoclient_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagestoclient',
            name='type_of_message',
            field=models.CharField(choices=[('Projects Reference', 'Projects Reference'), ('Workflow', 'Workflow'), ('Others', 'Others')], default='Others', max_length=100),
        ),
    ]
