# Generated by Django 3.0.8 on 2020-11-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsManagement', '0015_messagestoclient_type_of_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientsdetail',
            old_name='number_of_finalised_projects',
            new_name='number_of_finished_projects',
        ),
        migrations.AddField(
            model_name='clientsdetail',
            name='number_of_planned_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='messagestoclient',
            name='type_of_message',
            field=models.CharField(choices=[('Projects Reference', 'Projects Reference'), ('Workflow Reference', 'Workflow Reference'), ('Others', 'Others')], default='Others', max_length=100),
        ),
    ]
