# Generated by Django 3.0.8 on 2020-11-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsManagement', '0017_auto_20201108_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsrequest',
            name='project_request_slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
