# Generated by Django 3.0.8 on 2020-09-14 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainComponent', '0002_auto_20200914_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobappliance',
            name='carrer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MainComponent.AvaibleJob'),
        ),
    ]
