# Generated by Django 3.0.8 on 2020-09-15 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainComponent', '0003_auto_20200914_2029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobAppliance',
            new_name='JobsAppliance',
        ),
    ]
