# Generated by Django 3.0.8 on 2020-09-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainComponent', '0006_avaibleinternships'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvaibleInternships',
            new_name='AvaibleInternship',
        ),
    ]
