# Generated by Django 3.0.8 on 2020-09-28 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MainComponent', '0011_auto_20200927_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='moment',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
