# Generated by Django 3.0.8 on 2020-09-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainComponent', '0014_studio_moment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='moment',
            field=models.DateTimeField(),
        ),
    ]
