# Generated by Django 3.0.8 on 2020-09-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainComponent', '0016_studio_studio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaibleinternship',
            name='job_type',
            field=models.CharField(choices=[('Remote', 'Remote'), ('Non-Remote', 'Non-Remote')], default='Non-Remote', max_length=100),
        ),
        migrations.AddField(
            model_name='avaibleinternship',
            name='perks',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='avaiblejob',
            name='perks',
            field=models.CharField(default='', max_length=200),
        ),
    ]
