# Generated by Django 3.0.8 on 2020-10-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainComponent', '0018_auto_20201007_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='manager_words',
            field=models.TextField(default=''),
        ),
    ]
