# Generated by Django 3.0.8 on 2020-10-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainComponent', '0019_studio_manager_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='gallery_image_five',
            field=models.ImageField(default='default.jpg', upload_to='studios_gallery_images/'),
        ),
        migrations.AddField(
            model_name='studio',
            name='gallery_image_four',
            field=models.ImageField(default='default.jpg', upload_to='studios_gallery_images/'),
        ),
        migrations.AddField(
            model_name='studio',
            name='gallery_image_one',
            field=models.ImageField(default='default.jpg', upload_to='studios_gallery_images/'),
        ),
        migrations.AddField(
            model_name='studio',
            name='gallery_image_three',
            field=models.ImageField(default='default.jpg', upload_to='studios_gallery_images/'),
        ),
        migrations.AddField(
            model_name='studio',
            name='gallery_image_two',
            field=models.ImageField(default='default.jpg', upload_to='studios_gallery_images/'),
        ),
    ]
