# Generated by Django 3.0.8 on 2020-10-08 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainComponent', '0021_remove_internshipsappliance_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipsappliance',
            name='career',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MainComponent.AvailableInternship'),
        ),
    ]
