# Generated by Django 3.0.8 on 2020-10-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainComponent', '0022_auto_20201008_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipsappliance',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobsappliance',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
