# Generated by Django 3.0.8 on 2020-09-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainComponent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobappliance',
            name='carrer',
            field=models.CharField(default='', max_length=150),
        ),
    ]
