# Generated by Django 3.0.8 on 2020-09-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainComponent', '0015_auto_20200928_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='studio_image',
            field=models.ImageField(default='default.jpg', upload_to='studio_image/'),
        ),
    ]
