# Generated by Django 3.0.8 on 2020-10-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainComponent', '0024_auto_20201010_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('post', models.CharField(choices=[('Marketing Specialist', 'Marketing Specialist'), ('Web QA', 'Web QA'), ('Mobile QA', 'Mobile QA'), ('Software Developer', 'Software Developer'), ('Web Developer', 'Web Developer'), ('Web Designer', 'Web Designer'), ('Mobile Developer', 'Mobile Developer')], max_length=150)),
                ('experience', models.IntegerField()),
                ('profile_image', models.ImageField(upload_to='employers_images/')),
            ],
        ),
    ]
