# Generated by Django 3.0.8 on 2020-12-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainComponent', '0025_employer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_project', models.CharField(max_length=150)),
                ('project_image', models.ImageField(upload_to='projects_images/')),
                ('field', models.CharField(choices=[('Presentation WebSite', 'Presentation WebSite'), ('WebApp', 'Webapp'), ('Mobile App', 'Mobile App'), ('Marketing Project', 'Marketing Project')], max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='employer',
            name='post',
            field=models.CharField(choices=[('Marketing Specialist', 'Marketing Specialist'), ('Web QA', 'Web QA'), ('Mobile QA', 'Mobile QA'), ('Software Developer', 'Software Developer'), ('Web Developer', 'Web Developer'), ('Web Designer', 'Web Designer'), ('Mobile Developer', 'Mobile Developer'), ('Founder', 'Founder'), ('CoFounder', 'CoFounder')], max_length=150),
        ),
    ]
