# Generated by Django 3.0.8 on 2020-09-21 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsManagement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveWorkingProduct',
        ),
        migrations.DeleteModel(
            name='FinishedProduct',
        ),
        migrations.DeleteModel(
            name='PastProduct',
        ),
        migrations.DeleteModel(
            name='PlannedProduct',
        ),
    ]
