# Generated by Django 3.0.8 on 2020-08-17 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainView', '0006_auto_20200817_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmanswer',
            name='submitted',
        ),
    ]
