# Generated by Django 3.0.8 on 2020-11-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsManagement', '0019_auto_20201109_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsfeedback',
            name='content',
            field=models.TextField(),
        ),
    ]
