# Generated by Django 3.0.8 on 2020-09-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='wallpaper_representation',
        ),
    ]
