# Generated by Django 3.0.8 on 2020-09-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_remove_post_wallpaper_representation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='wallpaper_representation',
            field=models.ImageField(default='default.jpg', upload_to='wallpaper_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_representation',
            field=models.ImageField(default='default.jpg', upload_to='cover_images/'),
        ),
    ]
