# Generated by Django 3.0.8 on 2020-09-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20200903_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='sub_content_four',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_content_one',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_content_three',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_content_two',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_title_four',
            field=models.CharField(blank=True, default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_title_one',
            field=models.CharField(blank=True, default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_title_three',
            field=models.CharField(blank=True, default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_title_two',
            field=models.CharField(blank=True, default='', max_length=200, unique=True),
        ),
    ]
