# Generated by Django 3.0.8 on 2020-09-21 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveWorkingProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('list_of_functionalities', models.TextField()),
                ('type', models.CharField(choices=[('Presentation WebSite', 'Presentation WebSite'), ('WebApp', 'Webapp'), ('Mobile App', 'Mobile App')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FinishedProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('list_of_functionalities', models.TextField()),
                ('type', models.CharField(choices=[('Presentation WebSite', 'Presentation WebSite'), ('WebApp', 'Webapp'), ('Mobile App', 'Mobile App')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PastProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('list_of_functionalities', models.TextField()),
                ('type', models.CharField(choices=[('Presentation WebSite', 'Presentation WebSite'), ('WebApp', 'Webapp'), ('Mobile App', 'Mobile App')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlannedProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('list_of_functionalities', models.TextField()),
                ('type', models.CharField(choices=[('Presentation WebSite', 'Presentation WebSite'), ('WebApp', 'Webapp'), ('Mobile App', 'Mobile App')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlannedProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('list_of_functionalities', models.TextField()),
                ('type', models.CharField(choices=[('Presentation WebSite', 'Presentation WebSite'), ('WebApp', 'Webapp'), ('Mobile App', 'Mobile App')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PastProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('list_of_functionalities', models.TextField()),
                ('type', models.CharField(choices=[('Presentation WebSite', 'Presentation WebSite'), ('WebApp', 'Webapp'), ('Mobile App', 'Mobile App')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinishedProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('list_of_functionalities', models.TextField()),
                ('type', models.CharField(choices=[('Presentation WebSite', 'Presentation WebSite'), ('WebApp', 'Webapp'), ('Mobile App', 'Mobile App')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveWorkingProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('list_of_functionalities', models.TextField()),
                ('type', models.CharField(choices=[('Presentation WebSite', 'Presentation WebSite'), ('WebApp', 'Webapp'), ('Mobile App', 'Mobile App')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
