# Generated by Django 3.0.8 on 2020-08-14 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20200814_1107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
