# Generated by Django 3.0.8 on 2020-09-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsManagement', '0003_auto_20200922_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishedproduct',
            name='ready_for_delivery',
        ),
        migrations.AddField(
            model_name='activeworkingproduct',
            name='ready_for_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
