# Generated by Django 3.0.8 on 2020-10-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsManagement', '0004_auto_20200922_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeworkingproduct',
            name='type',
            field=models.CharField(choices=[('Presentation WebSite', 'Presentation WebSite'), ('WebApp', 'Webapp'), ('Mobile App', 'Mobile App'), ('Marketing Project', 'Marketing Project')], max_length=100),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='type',
            field=models.CharField(choices=[('Presentation WebSite', 'Presentation WebSite'), ('WebApp', 'Webapp'), ('Mobile App', 'Mobile App'), ('Marketing Project', 'Marketing Project')], max_length=100),
        ),
        migrations.AlterField(
            model_name='plannedproduct',
            name='type',
            field=models.CharField(choices=[('Presentation WebSite', 'Presentation WebSite'), ('WebApp', 'Webapp'), ('Mobile App', 'Mobile App'), ('Marketing Project', 'Marketing Project')], max_length=100),
        ),
    ]
