# Generated by Django 3.0.8 on 2020-09-22 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ClientsManagement', '0004_directclientcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_client', models.CharField(choices=[('Small Client', 'Small Client'), ('Medium Client', 'Medium Client'), ('Big Client', 'Big Client'), ('Huge Client', 'Huge Client')], max_length=100)),
                ('number_of_finalised_projects', models.IntegerField(default=0)),
                ('number_of_proposed_projects', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
