# Generated by Django 3.0.8 on 2020-10-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsManagement', '0010_messagestoclient_message_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsdetail',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='clients-profile_images'),
        ),
        migrations.AddField(
            model_name='clientsdetail',
            name='size_of_client',
            field=models.CharField(choices=[('Small Client', 'Small Client'), ('Medium Client', 'Medium Client'), ('Big Client', 'Big Client'), ('Huge Client', 'Huge Client')], default='Small Client', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientsdetail',
            name='type_of_client',
            field=models.CharField(choices=[('Self-employed Person', 'Self-employed Person'), ('StartUp', 'StartUp'), ('Company', 'Company'), ('Corporation', 'Corporation')], default='Self-employed Person', max_length=100),
        ),
    ]
