# Generated by Django 3.0.8 on 2020-11-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsManagement', '0016_auto_20201106_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagestoclient',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='projectsrequest',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='projectsrequest',
            name='project_status',
            field=models.CharField(choices=[('Waiting for Response', 'Waiting for Response'), ('Refused', 'Refused'), ('Accepted', 'Accepted')], default='Waiting for Response', max_length=100),
        ),
    ]
