# Generated by Django 3.0.8 on 2020-10-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsManagement', '0011_auto_20201024_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsrequest',
            name='type',
            field=models.CharField(choices=[('Presentation WebSite', 'Presentation WebSite'), ('WebApp', 'Webapp'), ('Mobile App', 'Mobile App'), ('Marketing Project', 'Marketing Project')], max_length=100),
        ),
    ]
