# Generated by Django 3.0.8 on 2020-10-10 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MainComponent', '0024_auto_20201010_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableInternship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.CharField(default='', max_length=150)),
                ('description', models.TextField(default='')),
                ('requirements', models.TextField(default='')),
                ('one_day', models.TextField(default='')),
                ('job_type', models.CharField(choices=[('Remote', 'Remote'), ('Non-Remote', 'Non-Remote')], default='Non-Remote', max_length=100)),
                ('perks', models.CharField(default='', max_length=200)),
                ('released_day', models.DateTimeField(auto_now_add=True)),
                ('internship_slug', models.SlugField(default='', max_length=200, unique=True)),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MainComponent.Studio')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.CharField(default='', max_length=150)),
                ('description', models.TextField(default='')),
                ('requirements', models.TextField(default='')),
                ('one_day', models.TextField(default='')),
                ('job_type', models.CharField(choices=[('Remote', 'Remote'), ('Non-Remote', 'Non-Remote')], default='Non-Remote', max_length=100)),
                ('perks', models.CharField(default='', max_length=200)),
                ('released_day', models.DateTimeField(auto_now_add=True)),
                ('job_slug', models.SlugField(default='', max_length=200, unique=True)),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MainComponent.Studio')),
            ],
        ),
        migrations.CreateModel(
            name='JobsAppliance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('curriculum_vitae', models.FileField(default='default.pdf', upload_to='curriculum_vitae/')),
                ('description_of_skills', models.TextField(default='')),
                ('accepted', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Careers.AvailableJob')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipsAppliance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('curriculum_vitae', models.FileField(default='default.pdf', upload_to='curriculum_vitae/')),
                ('description_of_skills', models.TextField(default='')),
                ('accepted', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Careers.AvailableInternship')),
            ],
        ),
    ]
