# Generated by Django 3.0.8 on 2020-09-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('space', models.CharField(max_length=200)),
                ('part_of_event', models.CharField(blank=True, max_length=200)),
                ('introduction', models.CharField(default='', max_length=300)),
                ('about_event', models.TextField(default='')),
                ('get_tickets', models.URLField()),
                ('location_image', models.ImageField(default='default.jpg', upload_to='events/locations/')),
                ('date', models.DateTimeField()),
                ('host_event_slug', models.SlugField(default='', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PastEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('space', models.CharField(max_length=200)),
                ('part_of_event', models.CharField(blank=True, max_length=200)),
                ('introduction', models.CharField(default='', max_length=300)),
                ('about_event', models.TextField(default='')),
                ('get_tickets', models.URLField()),
                ('location_image', models.ImageField(default='default.jpg', upload_to='events/locations/')),
                ('date', models.DateTimeField()),
                ('past_event_slug', models.SlugField(default='', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('space', models.CharField(max_length=200)),
                ('part_of_event', models.CharField(blank=True, max_length=200)),
                ('introduction', models.CharField(default='', max_length=300)),
                ('about_event', models.TextField(default='')),
                ('get_tickets', models.URLField()),
                ('location_image', models.ImageField(default='default.jpg', upload_to='events/locations/')),
                ('date', models.DateTimeField()),
                ('sponsor_event_slug', models.SlugField(default='', max_length=200, unique=True)),
            ],
        ),
    ]
