# Generated by Django 3.0.8 on 2020-09-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostevent',
            name='host_event_slug',
        ),
        migrations.RemoveField(
            model_name='pastevent',
            name='past_event_slug',
        ),
        migrations.RemoveField(
            model_name='sponsorevent',
            name='sponsor_event_slug',
        ),
    ]
