# Generated by Django 3.0.8 on 2020-09-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_auto_20200919_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostevent',
            old_name='host_event_slug',
            new_name='event_slug',
        ),
        migrations.RenameField(
            model_name='sponsorevent',
            old_name='sponsor_event_slug',
            new_name='event_slug',
        ),
    ]
