# Generated by Django 3.0.8 on 2020-10-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_auto_20200919_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastevent',
            name='cover_image',
            field=models.ImageField(default='default.jpg', upload_to='events/cover/'),
        ),
        migrations.AlterField(
            model_name='pastevent',
            name='location_image',
            field=models.ImageField(default='default.jpg', upload_to='events/location/'),
        ),
    ]
