# Generated by Django 3.0.8 on 2020-09-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsManagement', '0003_delete_pastproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedproject',
            name='working_status',
            field=models.CharField(choices=[('On Queue', 'On Queue'), ('Current Working at', 'Current Working at')], default='On Queue', max_length=100),
        ),
    ]
