# Generated by Django 3.0.8 on 2020-11-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsManagement', '0011_auto_20201109_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeworkingproject',
            name='project_classification',
            field=models.CharField(default='Active Working', max_length=100),
        ),
        migrations.AddField(
            model_name='finishedproject',
            name='project_classification',
            field=models.CharField(default='Finished', max_length=100),
        ),
        migrations.AddField(
            model_name='plannedproject',
            name='project_classification',
            field=models.CharField(default='Planned', max_length=100),
        ),
    ]
