# Generated by Django 3.0.8 on 2020-09-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_auto_20200919_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostevent',
            name='host_event_slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='pastevent',
            name='past_event_slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='sponsorevent',
            name='sponsor_event_slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
