# Generated by Django 3.0.8 on 2021-01-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=248)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
