# Generated by Django 3.0.8 on 2020-09-14 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('introduction', models.TextField(default='', unique=True)),
                ('sub_title_one', models.CharField(default='', max_length=200, unique=True)),
                ('sub_content_one', models.TextField(default='')),
                ('sub_title_two', models.CharField(default='', max_length=200, unique=True)),
                ('sub_content_two', models.TextField(default='')),
                ('sub_title_three', models.CharField(default='', max_length=200, unique=True)),
                ('sub_content_three', models.TextField(default='')),
                ('sub_title_four', models.CharField(default='', max_length=200, unique=True)),
                ('sub_content_four', models.TextField(default='')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('cover_representation', models.ImageField(default='default.jpg', upload_to='cover_images/')),
                ('wallpaper_representation', models.ImageField(default='default.jpg', upload_to='wallpaper_images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
