# Generated by Django 3.1.7 on 2021-03-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0003_adminresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='calendar',
            new_name='desired_date',
        ),
    ]
