# Generated by Django 3.1.7 on 2021-03-05 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0004_auto_20210304_2051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminResponse',
        ),
    ]
