# Generated by Django 3.0.8 on 2020-11-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsManagement', '0018_projectsrequest_project_request_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsfeedback',
            name='content',
            field=models.TextField(default='default.jpg'),
        ),
    ]
