# Generated by Django 3.0.8 on 2020-11-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsManagement', '0022_auto_20201109_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsdetail',
            name='profile_image',
            field=models.ImageField(default='MEDIA/clients-profile-images/ceva.jpg', upload_to='clients-profile-images/'),
        ),
    ]
