# Generated by Django 3.0.8 on 2020-09-27 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainComponent', '0007_auto_20200927_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipsAppliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('curriculum_vitae', models.FileField(default='default.pdf', upload_to='curriculum_vitae/')),
                ('description_of_skills', models.TextField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('carrer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MainComponent.AvaibleJob')),
            ],
        ),
    ]
